env:
  browser: true
  es6: true
extends:
  - plugin:@typescript-eslint/recommended
  - standard
  - prettier
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  "@typescript-eslint/indent": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/ban-ts-ignore": 0
  "@typescript-eslint/no-namespace": 0
  "@typescript-eslint/no-empty-function": 0
  prettier/prettier: 2
  no-unused-vars: 0
  node/no-unsupported-features/es-syntax: 0